name: Monitor Folder Changes

on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at midnight UTC

jobs:
  check_for_changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        repository: QubinoHelp/Shelly_Wave_FW_OTA
        path: target-repo

    - name: Check for Changes
      id: check_changes
      run: |
        cd target-repo/Wave_2PM/EU
        git fetch origin
        CHANGES=$(git diff --name-only HEAD origin/main)
        echo "::set-output name=changes::$CHANGES"

    - name: Create GitHub Issue
      if: steps.check_changes.outputs.changes != ''
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: "Changes detected in Wave_2PM/EU folder"
        content-filepath: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
